### ISSUE TITLE
project backlog

### ISSUE THREAD

**Issue by lunify** [chingu-voyages/v10-bears-team-07#3]
Come up with the set of core functionalities that our MVP will have, and transform them to user stories.

The format of the tasks will be Epics > user stories > subtasks
The equivalent in Github will be Epics > Github issues > markdown task lists

**Comment by lunify** [comment]
This is the initial set of core functionalities that come to mind
- [x] Splash page - Project discovery
- [x] Authentication - Access to the app
- [x] Channel creation
- [x] Channel search
- [ ] Channel subscription/opt-out
- [ ] Channel discussion - community chat
- [ ] Ownership transfer
- [ ] User settings
- [ ] User availability
- [ ] Channel moderation

Anything that needs to be added/discussed or should we add this to our backlog ?

**Comment by yapanss** [comment]
I accept these tasks. Maybe somme additions later

**Comment by lunify** [comment]
With that, I'm closing it until we finish our current backlog

**Comment by yapanss** [comment]
Ok.
